### ISSUE TITLE
Remove Unused JS (Optimise Js)

### ISSUE THREAD

**Issue by TecnikOfficial** [TecnikOfficial/TecnikOfficial.github.io#5]
manually doing it takes time if possible can someone use webpack /terser or any other method to quickly do that 
[js](https://github.com/techgamers2/tecnik/tree/main/js) > ``plugins0a05.js`` and ``hero0a05.js``

**Comment by techgamers2** [comment]
combined js to min.js

**Comment by TecnikOfficial** [comment]
site lags on some low end mobile device ( hardware acceleration give better performance ) need to remove unused js

**Comment by TecnikOfficial** [comment]
remove motion sensor code

**Comment by TecnikOfficial** [comment]
no longer needed
